services:
  postgres:
    container_name: church-postgres
    image: 'postgres:latest'
    environment:
      POSTGRES_DB: church
      POSTGRES_PASSWORD: mawuli302
      POSTGRES_USER: mawuli
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5222:5432"
    restart: always
volumes:
  db: