server:
  port: 5000
  error:
    include-binding-errors: always

spring:
  datasource:
    url: jdbc:postgresql://localhost:5222/church
    username: mawuli
    password: mawuli302
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show_sql: true
